### ISSUE TITLE
如何增加manual craft machine的效率呢

### ISSUE THREAD

**Issue by RAURORA2** [ecro-fun/FinalTECH#13]
能否改成类似于以前的机制但是限制每秒点击次数，现在这个增长太慢了

**Comment by ecro-fun** [comment]
请详细描述问题

**Comment by RAURORA2** [comment]
> 请详细描述问题

就是怎么调整manual craft machine这类机器的效率，我希望默认增长为1j/s，通过玩家的点击最高能到64j/s，但是现在的不管咋点击好像最多快一点

**Comment by RAURORA2** [comment]
> 请详细描述问题

通过上次对这个手动机器的平衡更新之后，感觉这个效率实在是太慢了，我想调高一点
