### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by RAURORA2** [ecro-fun/FinalTECH#15]
## Server Log / Error Report

[error.txt](https://github.com/ecro-fun/FinalTECH/files/10833154/error.txt)

## Environment (Required)

 - Minecraft Version:purpur1.19.2
 - CS-CoreLib Version:
 - Slimefun Version:va88d0e0
 - Plugin Version:

**Comment by ecro-fun** [comment]
是否对FinalTECH的config.yml做过任何手动修改？

**Comment by RAURORA2** [comment]
没有，我为了防止从老版本升级到新版本出现什么问题，用的还是刚刚删掉以后新生成的。

**Comment by ecro-fun** [comment]
除非该报错经常发生，请无视该报错。
