### ISSUE TITLE
后台无限报错

### ISSUE THREAD

**Issue by RAURORA2** [ecro-fun/FinalTECH#16]
## Description (Required)

后台无限报错
## Steps to reproduce the Issue (Required)

服务器启动完就开始一直报错
## Server Log / Error Report

[error.txt](https://github.com/ecro-fun/FinalTECH/files/11071054/error.txt)

## Environment (Required)

 - Minecraft Version:purpur1.19.2
 - CS-CoreLib Version:
 - Slimefun Version:Slimefun-6889670-canary
 - Plugin Version: FinalTech-Build 72 zh-CN(ECRO) (git 1799eb2)

**Comment by ecro-fun** [comment]
暂时回退 Slimefun 版本，或等待 FinalTech 更新

**Comment by HiTech0926** [comment]
@ecro-fun FinalTech 何时更新？
When will FinalTech be updated?

**Comment by ecro-fun** [comment]
> @ecro-fun FinalTech 何时更新？ When will FinalTech be updated?

There are a lot of changes in the next version that will take a lot of time to complete
