### ISSUE TITLE
矩阵合成台无法正常使用

### ISSUE THREAD

**Issue by JIAFALSEDREAM** [ecro-fun/FinalTECH#9]
矩阵合成台无法正常使用
例:
/sf cheat 获取无序有序尘埃伪物
/finaltech-copy-card 使2种尘埃变为复制卡
依照合成表把物品放入矩阵合成台
![9c08e394daef0704f3bab342ba896dd](https://user-images.githubusercontent.com/121747365/216824500-a9d9ada7-3a4c-48b2-b619-24e61bf95cfb.png)
![a6defa5473b5015278a57d15d8d8dd2](https://user-images.githubusercontent.com/121747365/216824504-9cb85213-a676-4969-935e-11b930e85812.png)

合成处显示无效,点击无反应

将合成配方上下移动也没有反应
![3da33341d9b83ea694ea15ea4caf79f](https://user-images.githubusercontent.com/121747365/216824562-5e344702-4926-45b4-b7e5-15c46e64c0de.png)

其他需要矩阵合成台的物品大部分也无法制造

点击合成后台无报错

![195ee565ffcc15ff88ef3a4548594a3](https://user-images.githubusercontent.com/121747365/216824618-111ba45a-6d89-4628-92d5-5e09f8763cdc.png)

**Comment by ecro-fun** [comment]
具体哪些物品无法合成？能否给出一个清单？

**Comment by JIAFALSEDREAM** [comment]
因为是玩家反馈的bug
不清楚有哪些不可以合成
最近应该没空去尝试

**Comment by JIAFALSEDREAM** [comment]
因为玩家反馈
不知道有哪些不可以合成
如果需要不可合成的名单可能要等一段时间
